# Site settings
title: "Búri: a Homebrew 6502 Computer"
email: rich.buri@richwareham.com
description: > # this means to ignore newlines until "baseurl:"
  An experiment in learning electronics and low-level software through a
  personal project to recreate a 1980s-style home computer.
baseurl: "/buri/" # the subpath of your site, e.g. /blog/
url: "https://rjw57.github.io/" # the base hostname & protocol for your site
twitter_username: richwareham
github_username:  rjw57

# Build settings
markdown: kramdown

exclude: [Makefile, README.md]
